services:
  postgres:
    container_name: pg_container
    image: postgres
    restart: always        
    environment:
      POSTGRES_PASSWORD: rm045369
    ports:
      - '5455:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data