version: '3'
services:
#GenerateBackendBuild
  HungerAPI:
    build:
     context: .
     dockerfile: Dockerfile
    image: "hunger-api"
    restart: always
    container_name: dockerComposeHungerApi
    networks:
     - hunger-net
    ports:
     - '8081:8081'
networks :
  hunger-net :
